name: paypal_payment
description: Dart package for paypal payment integration in all platforms.
version: 1.0.0+3
repository: https://github.com/code-Shabbir/paypal_payment.git

environment:
  sdk: ">=2.19.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  dio: ^5.5.0+1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
